# Generated by Django 5.0.6 on 2024-05-30 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feeding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeding',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='finch',
            old_name='species',
            new_name='breed',
        ),
    ]
